### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by robertsawko** [BenMql/2decomp_emptyFourierFourier#1]
Hi Ben,

Again, as part of the [review checkilist](https://github.com/openjournals/joss-reviews/issues/2978) I am verifying the build instructions you have given in [here](https://github.com/BenMql/coral/wiki/1_Installation) for Coral and [here](https://github.com/BenMql/coral/wiki/Decomp2d_installation) for 2decompo library. I have FFTW 3.3.9-1 installed from a package manager and it sits in `/usr/{lib,include,...}`.

I copy the Makefile and modify accordingly, but the build fails with:
```
make[2]: Entering directory '/home/rsa/documents/reviews/to_review/miquel2021/2decomp_emptyFourierFourier/examples/test2d'
mpif90 -I../../include -DDOUBLE_PREC -O3 -fcray-pointer -cpp -I/usr//include -c test2d.f90
f951: Warning: Nonexistent include directory ‘../../include’ [-Wmissing-include-dirs]
test2d.f90:3:7:

    3 |   use decomp_2d
      |       1
Fatal Error: Cannot open module file ‘decomp_2d.mod’ for reading at (1): No such file or directory
compilation terminated.

```

Please advise.

**Comment by BenMql** [comment]
Hi Robert, 
I have identified the issue: an 'include' folder should be created at the root of the 2decomp library. I modified the 2decomp installation instructions accordingly. 
Let me know if the problem still exists.

**Comment by robertsawko** [comment]
Yes. Thanks. All compiled now.
